name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        run: cypress run --spec 'cypress/integration/advanced/cyget.spec.js'
        working-directory: ./cypress-practice


